language: bash

before_install:
- wget https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/1000G_omni2.5.hg38.vcf.gz
- zcat 1000G_omni2.5.hg38.vcf.gz > 1000G_omni2.5.hg38.vcf

# Actual tests
script: "./vcfShrinker.sh -p 10 -v 1000G_omni2.5.hg38.vcf"